return {
	desc = "永不结束的饥荒沙盒模式。永远可以在绚丽之门复活。",
	hideminimap = false,
	id = "ENDLESS",
	location = "forest",
	max_playlist_position = 999,
	min_playlist_position = 0,
	name = "无尽",
	numrandom_set_pieces = 4,
	override_level_string = false,
	overrides = {
    season_start = "default",
    loop = "default",
    start_location = "default",
    touchstone = "default",
    roads = "default",
    stageplays = "default",
    terrariumchest = "default",
    moon_fissure = "default",
    prefabswaps_start = "default",
    world_size = "default",
    task_set = "default",
    boons = "default",
    branching = "default",
    moon_sapling = "default",
    meteorspawner = "default",
    rock_ice = "default",
    rock = "default",
    mushroom = "default",
    ocean_bullkelp = "default",
    trees = "default",
    flint = "default",
    flowers = "default",
    moon_starfish = "default",
    marshbush = "default",
    tumbleweed = "default",
    reeds = "default",
    moon_hotspring = "default",
    moon_berrybush = "default",
    berrybush = "default",
    palmconetree = "default",
    carrot = "default",
    cactus = "default",
    sapling = "default",
    ponds = "default",
    moon_bullkelp = "default",
    moon_tree = "default",
    grass = "default",
    ocean_seastack = "ocean_default",
    moon_rock = "default",
    bees = "default",
    ocean_shoal = "default",
    pigs = "default",
    moon_carrot = "default",
    lightninggoat = "default",
    moles = "default",
    catcoon = "default",
    rabbits = "default",
    beefalo = "default",
    buzzard = "default",
    ocean_wobsterden = "default",
    moon_fruitdragon = "default",
    tentacles = "default",
    tallbirds = "default",
    angrybees = "default",
    ocean_waterplant = "ocean_default",
    houndmound = "default",
    walrus = "default",
    chess = "default",
    merm = "default",
    spiders = "default",
    moon_spiders = "default",
    spring = "default",
    autumn = "default",
    krampus = "default",
    beefaloheat = "default",
    summer = "default",
    winter = "default",
    ghostenabled = "always",
    spawnmode = "fixed",
    day = "default",
    resettime = "default",
    ghostsanitydrain = "always",
    specialevent = "default",
    portalresurection = "none",
    year_of_the_beefalo = "default",
    year_of_the_carrat = "default",
    hallowed_nights = "default",
    year_of_the_catcoon = "default",
    year_of_the_varg = "default",
    winters_feast = "default",
    crow_carnival = "default",
    year_of_the_gobbler = "default",
    year_of_the_bunnyman = "default",
    year_of_the_pig = "default",
    spawnprotection = "default",
    dropeverythingondespawn = "default",
    healthpenalty = "always",
    lessdamagetaken = "none",
    brightmarecreatures = "default",
    darkness = "default",
    temperaturedamage = "default",
    shadowcreatures = "default",
    hunger = "default",
    extrastartingitems = "default",
    seasonalstartingitems = "default",
    alternatehunt = "default",
    frograin = "default",
    meteorshowers = "default",
    rifts_enabled = "default",
    weather = "default",
    hounds = "default",
    wildfires = "default",
    lightning = "default",
    hunt = "default",
    summerhounds = "default",
    petrification = "default",
    rifts_frequency = "default",
    winterhounds = "default",
    flowers_regrowth = "default",
    basicresource_regrowth = "none",
    twiggytrees_regrowth = "default",
    moon_tree_regrowth = "default",
    deciduoustree_regrowth = "default",
    regrowth = "default",
    reeds_regrowth = "default",
    carrots_regrowth = "default",
    palmconetree_regrowth = "default",
    saltstack_regrowth = "default",
    cactus_regrowth = "default",
    evergreen_regrowth = "default",
    lightcrab_portalrate = "default",
    portal_spawnrate = "default",
    powder_monkey_portalrate = "default",
    palmcone_seed_portalrate = "default",
    monkeytail_portalrate = "default",
    bananabush_portalrate = "default",
    penguins = "default",
    perd = "default",
    grassgekkos = "default",
    birds = "default",
    catcoons = "default",
    moles_setting = "default",
    bees_setting = "default",
    fishschools = "default",
    pigs_setting = "default",
    rabbits_setting = "default",
    bunnymen_setting = "default",
    butterfly = "default",
    gnarwail = "default",
    wobsters = "default",
    wasps = "default",
    bats_setting = "default",
    penguins_moon = "default",
    lureplants = "default",
    frogs = "default",
    pirateraids = "default",
    mutated_hounds = "default",
    moon_spider = "default",
    sharks = "default",
    mosquitos = "default",
    spider_warriors = "default",
    hound_mounds = "default",
    walrus_setting = "default",
    squid = "default",
    merms = "default",
    cookiecutters = "default",
    spiders_setting = "default",
    crabking = "default",
    antliontribute = "default",
    malbatross = "default",
    eyeofterror = "default",
    liefs = "default",
    spiderqueen = "default",
    bearger = "default",
    klaus = "default",
    deciduousmonster = "default",
    beequeen = "default",
    dragonfly = "default",
    goosemoose = "default",
    fruitfly = "default",
    deerclops = "default",
    has_ocean = true,
    keep_disconnected_tiles = true,
    layout_mode = "LinkNodesByKeys",
    no_joining_islands = true,
    no_wormholes_to_disconnected_tiles = true,
    wormhole_prefab = "wormhole",},
	playstyle = "endless",
	random_set_pieces = {
		"Sculptures_2",
		"Sculptures_3",
		"Sculptures_4",
		"Sculptures_5",
		"Chessy_1",
		"Chessy_2",
		"Chessy_3",
		"Chessy_4",
		"Chessy_5",
		"Chessy_6",
		"Maxwell1",
		"Maxwell2",
		"Maxwell3",
		"Maxwell4",
		"Maxwell6",
		"Maxwell7",
		"Warzone_1",
		"Warzone_2",
		"Warzone_3",
	},
	required_prefabs = {
		"multiplayer_portal",
	},
	required_setpieces = {
		"Sculptures_1",
		"Maxwell5",
	},
	settings_desc = "永不结束的饥荒沙盒模式。永远可以在绚丽之门复活。",
	settings_id = "ENDLESS",
	settings_name = "无尽",
	substitutes = {},
	version = 4,
	worldgen_desc = "永不结束的饥荒沙盒模式。永远可以在绚丽之门复活。",
	worldgen_id = "ENDLESS",
	worldgen_name = "无尽",
}